### ISSUE TITLE
책 기록 추가 API

### ISSUE THREAD

**Issue by minseoooooo** [BookwooriAlpineClub/Bookwoori-Back#58]

**Comment by crhwang822** [comment]
- [ ] 📅 2024-11-29 책 기록 중복 저장되는 문제
  ![image](https://github.com/user-attachments/assets/accf4f97-e7c2-49c4-a91a-10b9c23fa3a4)
  - bookId와 memberId를 이용해 중복 검사해야 할 것 같습니다!
